$(document).ready(function(){
    $('.slide1').slick({
        autoplay:true,
        autoplaySpeed:4000,
        dots:false,
        infinite:true,
        speed:900,
        fade:false,
        rt1:true,
        pauseOnHover:false,
        touchMove:true,
        arrows:false
    });
});